# Generated by Django 4.0.3 on 2022-04-04 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_myuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='date_of_birth',
        ),
    ]
